/**
 * EC API
 * E-Commerce REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreatePermissionDto {
    /**
    * Module
    */
    'module': string;
    'action': CreatePermissionDtoActionEnum;
    'description'?: string;
    /**
    * Đánh dấu permission hệ thống
    */
    'isSystem'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "module",
            "baseName": "module",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "CreatePermissionDtoActionEnum",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isSystem",
            "baseName": "isSystem",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreatePermissionDto.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreatePermissionDtoActionEnum {
    Create = 'create',
    Read = 'read',
    Update = 'update',
    Delete = 'delete',
    Cancel = 'cancel',
    Publish = 'publish',
    AssignRole = 'assign.role'
}

