/**
 * EC API
 * E-Commerce REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Permission {
    /**
    * ID permission
    */
    'id': string;
    /**
    * Module
    */
    'module': string;
    /**
    * Hành động CRUD
    */
    'action': PermissionActionEnum;
    'description'?: string;
    /**
    * Permission hệ thống (readonly)
    */
    'isSystem': boolean;
    'createdAt': Date;
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "module",
            "baseName": "module",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "PermissionActionEnum",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isSystem",
            "baseName": "isSystem",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Permission.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PermissionActionEnum {
    Create = 'create',
    Read = 'read',
    Update = 'update',
    Delete = 'delete',
    Cancel = 'cancel',
    Publish = 'publish',
    AssignRole = 'assign.role'
}

