/**
 * EC API
 * E-Commerce REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PermissionMetaResponseDto {
    /**
    * Danh sách module hiện có
    */
    'modules': Array<string>;
    /**
    * Danh sách action hệ thống (CRUD)
    */
    'systemActions': Array<string>;
    /**
    * Danh sách action custom (non-system)
    */
    'customActions': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "systemActions",
            "baseName": "systemActions",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "customActions",
            "baseName": "customActions",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PermissionMetaResponseDto.attributeTypeMap;
    }

    public constructor() {
    }
}
