/**
 * EC API
 * E-Commerce REST API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PermissionResponseDto } from '../models/PermissionResponseDto';
import { HttpFile } from '../http/http';

export class RoleResponseDto {
    /**
    * Role unique identifier
    */
    'id': string;
    /**
    * Role name
    */
    'name': string;
    /**
    * Role description
    */
    'description'?: string;
    /**
    * Role creation date
    */
    'createdAt': Date;
    /**
    * Role last update date
    */
    'updatedAt': Date;
    /**
    * Permissions assigned to this role
    */
    'permissions'?: Array<PermissionResponseDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<PermissionResponseDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RoleResponseDto.attributeTypeMap;
    }

    public constructor() {
    }
}
