// This file is auto-generated by @hey-api/openapi-ts

import type { AdminBannersControllerCreateResponse, AdminBannersControllerFindAllResponse, AdminBannersControllerUpdateResponse, AdminBannersControllerUploadImageResponse, AdminCategoriesControllerCreateResponse, AdminCategoriesControllerFindAllResponse, AdminCategoriesControllerFindOneResponse, AdminCategoriesControllerFindTreeResponse, AdminCategoriesControllerRemoveImageResponse, AdminCategoriesControllerUpdateResponse, AdminCategoriesControllerUploadImageResponse, AdminDiscountsControllerCreateResponse, AdminDiscountsControllerFindAllResponse, AdminDiscountsControllerFindOneResponse, AdminDiscountsControllerUpdateResponse, AdminOrdersControllerFindAllResponse, AdminOrdersControllerFindOneResponse, AdminOrdersControllerUpdateStatusResponse, AdminPaymentsControllerFindAllResponse, AdminPaymentsControllerFindOneResponse, AdminPaymentsControllerUpdateStatusResponse, AdminPermissionsControllerCreateResponse, AdminPermissionsControllerFindAllResponse, AdminPermissionsControllerFindOneResponse, AdminPermissionsControllerUpdateResponse, AdminProductsControllerAddVariantResponse, AdminProductsControllerCreateResponse, AdminProductsControllerFindAllResponse, AdminProductsControllerFindOneResponse, AdminProductsControllerUpdateResponse, AdminProductsControllerUpdateVariantResponse, AdminReviewsControllerApproveResponse, AdminReviewsControllerFindAllResponse, AdminRolesControllerAssignPermissionsResponse, AdminRolesControllerCreateRoleResponse, AdminRolesControllerFindAllResponse, AdminRolesControllerFindOneResponse, AdminRolesControllerUpdateResponse, AdminUsersControllerAssignPermissionsResponse, AdminUsersControllerAssignRolesResponse, AdminUsersControllerFindAllResponse, AdminUsersControllerFindByUserCodeResponse, AdminUsersControllerFindOneResponse, AdminUsersControllerUpdateResponse } from './types.gen';

const permissionResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const roleResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    if (data.permissions) {
        data.permissions = data.permissions.map((item: any) => permissionResponseDtoSchemaResponseTransformer(item));
    }
    return data;
};

const userResponseDtoSchemaResponseTransformer = (data: any) => {
    data.roles = data.roles.map((item: any) => roleResponseDtoSchemaResponseTransformer(item));
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const userPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => userResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminUsersControllerFindAllResponseTransformer = async (data: any): Promise<AdminUsersControllerFindAllResponse> => {
    data = userPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const userDetailDtoSchemaResponseTransformer = (data: any) => {
    data.roles = data.roles.map((item: any) => roleResponseDtoSchemaResponseTransformer(item));
    data.permissions = data.permissions.map((item: any) => permissionResponseDtoSchemaResponseTransformer(item));
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const adminUsersControllerFindByUserCodeResponseTransformer = async (data: any): Promise<AdminUsersControllerFindByUserCodeResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

export const adminUsersControllerFindOneResponseTransformer = async (data: any): Promise<AdminUsersControllerFindOneResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

export const adminUsersControllerUpdateResponseTransformer = async (data: any): Promise<AdminUsersControllerUpdateResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

export const adminUsersControllerAssignRolesResponseTransformer = async (data: any): Promise<AdminUsersControllerAssignRolesResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

export const adminUsersControllerAssignPermissionsResponseTransformer = async (data: any): Promise<AdminUsersControllerAssignPermissionsResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

const rolePaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => roleResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminRolesControllerFindAllResponseTransformer = async (data: any): Promise<AdminRolesControllerFindAllResponse> => {
    data = rolePaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminRolesControllerCreateRoleResponseTransformer = async (data: any): Promise<AdminRolesControllerCreateRoleResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminRolesControllerFindOneResponseTransformer = async (data: any): Promise<AdminRolesControllerFindOneResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminRolesControllerUpdateResponseTransformer = async (data: any): Promise<AdminRolesControllerUpdateResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminRolesControllerAssignPermissionsResponseTransformer = async (data: any): Promise<AdminRolesControllerAssignPermissionsResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

const permissionPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => permissionResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminPermissionsControllerFindAllResponseTransformer = async (data: any): Promise<AdminPermissionsControllerFindAllResponse> => {
    data = permissionPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const permissionSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const adminPermissionsControllerCreateResponseTransformer = async (data: any): Promise<AdminPermissionsControllerCreateResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};

export const adminPermissionsControllerFindOneResponseTransformer = async (data: any): Promise<AdminPermissionsControllerFindOneResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};

export const adminPermissionsControllerUpdateResponseTransformer = async (data: any): Promise<AdminPermissionsControllerUpdateResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};

const categoryResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const categoryPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => categoryResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminCategoriesControllerFindAllResponseTransformer = async (data: any): Promise<AdminCategoriesControllerFindAllResponse> => {
    data = categoryPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const adminCategoryResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const adminCategoriesControllerCreateResponseTransformer = async (data: any): Promise<AdminCategoriesControllerCreateResponse> => {
    data = adminCategoryResponseDtoSchemaResponseTransformer(data);
    return data;
};

const categoryTreeNodeDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    if (data.children) {
        data.children = data.children.map((item: any) => categoryTreeNodeDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const adminCategoriesControllerFindTreeResponseTransformer = async (data: any): Promise<AdminCategoriesControllerFindTreeResponse> => {
    data = data.map((item: any) => categoryTreeNodeDtoSchemaResponseTransformer(item));
    return data;
};

export const adminCategoriesControllerFindOneResponseTransformer = async (data: any): Promise<AdminCategoriesControllerFindOneResponse> => {
    data = adminCategoryResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminCategoriesControllerUpdateResponseTransformer = async (data: any): Promise<AdminCategoriesControllerUpdateResponse> => {
    data = adminCategoryResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminCategoriesControllerUploadImageResponseTransformer = async (data: any): Promise<AdminCategoriesControllerUploadImageResponse> => {
    data = adminCategoryResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminCategoriesControllerRemoveImageResponseTransformer = async (data: any): Promise<AdminCategoriesControllerRemoveImageResponse> => {
    data = adminCategoryResponseDtoSchemaResponseTransformer(data);
    return data;
};

const productListItemDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const productPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => productListItemDtoSchemaResponseTransformer(item));
    return data;
};

export const adminProductsControllerFindAllResponseTransformer = async (data: any): Promise<AdminProductsControllerFindAllResponse> => {
    data = productPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const productVariantResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const adminProductResponseDtoSchemaResponseTransformer = (data: any) => {
    data.variants = data.variants.map((item: any) => productVariantResponseDtoSchemaResponseTransformer(item));
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const adminProductsControllerCreateResponseTransformer = async (data: any): Promise<AdminProductsControllerCreateResponse> => {
    data = adminProductResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminProductsControllerFindOneResponseTransformer = async (data: any): Promise<AdminProductsControllerFindOneResponse> => {
    data = adminProductResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminProductsControllerUpdateResponseTransformer = async (data: any): Promise<AdminProductsControllerUpdateResponse> => {
    data = adminProductResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminProductsControllerAddVariantResponseTransformer = async (data: any): Promise<AdminProductsControllerAddVariantResponse> => {
    data = productVariantResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminProductsControllerUpdateVariantResponseTransformer = async (data: any): Promise<AdminProductsControllerUpdateVariantResponse> => {
    data = productVariantResponseDtoSchemaResponseTransformer(data);
    return data;
};

const adminOrderListItemDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const adminOrderPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => adminOrderListItemDtoSchemaResponseTransformer(item));
    return data;
};

export const adminOrdersControllerFindAllResponseTransformer = async (data: any): Promise<AdminOrdersControllerFindAllResponse> => {
    data = adminOrderPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const adminOrderResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const adminOrdersControllerFindOneResponseTransformer = async (data: any): Promise<AdminOrdersControllerFindOneResponse> => {
    data = adminOrderResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminOrdersControllerUpdateStatusResponseTransformer = async (data: any): Promise<AdminOrdersControllerUpdateStatusResponse> => {
    data = adminOrderResponseDtoSchemaResponseTransformer(data);
    return data;
};

const adminDiscountResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const adminDiscountPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => adminDiscountResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminDiscountsControllerFindAllResponseTransformer = async (data: any): Promise<AdminDiscountsControllerFindAllResponse> => {
    data = adminDiscountPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminDiscountsControllerCreateResponseTransformer = async (data: any): Promise<AdminDiscountsControllerCreateResponse> => {
    data = adminDiscountResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminDiscountsControllerFindOneResponseTransformer = async (data: any): Promise<AdminDiscountsControllerFindOneResponse> => {
    data = adminDiscountResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminDiscountsControllerUpdateResponseTransformer = async (data: any): Promise<AdminDiscountsControllerUpdateResponse> => {
    data = adminDiscountResponseDtoSchemaResponseTransformer(data);
    return data;
};

const adminPaymentResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const adminPaymentPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => adminPaymentResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminPaymentsControllerFindAllResponseTransformer = async (data: any): Promise<AdminPaymentsControllerFindAllResponse> => {
    data = adminPaymentPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminPaymentsControllerFindOneResponseTransformer = async (data: any): Promise<AdminPaymentsControllerFindOneResponse> => {
    data = adminPaymentResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminPaymentsControllerUpdateStatusResponseTransformer = async (data: any): Promise<AdminPaymentsControllerUpdateStatusResponse> => {
    data = adminPaymentResponseDtoSchemaResponseTransformer(data);
    return data;
};

const adminReviewResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const adminReviewPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => adminReviewResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminReviewsControllerFindAllResponseTransformer = async (data: any): Promise<AdminReviewsControllerFindAllResponse> => {
    data = adminReviewPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminReviewsControllerApproveResponseTransformer = async (data: any): Promise<AdminReviewsControllerApproveResponse> => {
    data = adminReviewResponseDtoSchemaResponseTransformer(data);
    return data;
};

const adminBannerResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const adminBannersControllerFindAllResponseTransformer = async (data: any): Promise<AdminBannersControllerFindAllResponse> => {
    data = data.map((item: any) => adminBannerResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const adminBannersControllerCreateResponseTransformer = async (data: any): Promise<AdminBannersControllerCreateResponse> => {
    data = adminBannerResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminBannersControllerUploadImageResponseTransformer = async (data: any): Promise<AdminBannersControllerUploadImageResponse> => {
    data = adminBannerResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const adminBannersControllerUpdateResponseTransformer = async (data: any): Promise<AdminBannersControllerUpdateResponse> => {
    data = adminBannerResponseDtoSchemaResponseTransformer(data);
    return data;
};
