// This file is auto-generated by @hey-api/openapi-ts

import type { PermissionsControllerCreateResponse, PermissionsControllerFindAllResponse, PermissionsControllerFindOneResponse, PermissionsControllerUpdateResponse, RolesControllerAssignPermissionsResponse, RolesControllerCreateRoleResponse, RolesControllerFindAllResponse, RolesControllerFindOneResponse, RolesControllerUpdateResponse } from './types.gen';

const permissionResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const roleResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    if (data.permissions) {
        data.permissions = data.permissions.map((item: any) => permissionResponseDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const rolesControllerFindAllResponseTransformer = async (data: any): Promise<RolesControllerFindAllResponse> => {
    data = data.map((item: any) => roleResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const rolesControllerCreateRoleResponseTransformer = async (data: any): Promise<RolesControllerCreateRoleResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const rolesControllerFindOneResponseTransformer = async (data: any): Promise<RolesControllerFindOneResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const rolesControllerUpdateResponseTransformer = async (data: any): Promise<RolesControllerUpdateResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const rolesControllerAssignPermissionsResponseTransformer = async (data: any): Promise<RolesControllerAssignPermissionsResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

const permissionSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const permissionsControllerFindAllResponseTransformer = async (data: any): Promise<PermissionsControllerFindAllResponse> => {
    data = data.map((item: any) => permissionSchemaResponseTransformer(item));
    return data;
};

export const permissionsControllerCreateResponseTransformer = async (data: any): Promise<PermissionsControllerCreateResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};

export const permissionsControllerFindOneResponseTransformer = async (data: any): Promise<PermissionsControllerFindOneResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};

export const permissionsControllerUpdateResponseTransformer = async (data: any): Promise<PermissionsControllerUpdateResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};
