// This file is auto-generated by @hey-api/openapi-ts

import type { PermissionsControllerCreateResponse, PermissionsControllerFindAllResponse, PermissionsControllerFindOneResponse, PermissionsControllerUpdateResponse, RolesControllerAssignPermissionsResponse, RolesControllerCreateRoleResponse, RolesControllerFindAllResponse, RolesControllerFindOneResponse, RolesControllerUpdateResponse, UsersControllerAssignPermissionsResponse, UsersControllerAssignRolesResponse, UsersControllerFindAllResponse, UsersControllerFindOneResponse, UsersControllerUpdateResponse } from './types.gen';

const permissionResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const roleResponseDtoSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    if (data.permissions) {
        data.permissions = data.permissions.map((item: any) => permissionResponseDtoSchemaResponseTransformer(item));
    }
    return data;
};

const userResponseDtoSchemaResponseTransformer = (data: any) => {
    data.roles = data.roles.map((item: any) => roleResponseDtoSchemaResponseTransformer(item));
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const userPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => userResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const usersControllerFindAllResponseTransformer = async (data: any): Promise<UsersControllerFindAllResponse> => {
    data = userPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const userDetailDtoSchemaResponseTransformer = (data: any) => {
    data.roles = data.roles.map((item: any) => roleResponseDtoSchemaResponseTransformer(item));
    data.permissions = data.permissions.map((item: any) => permissionResponseDtoSchemaResponseTransformer(item));
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const usersControllerFindOneResponseTransformer = async (data: any): Promise<UsersControllerFindOneResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

export const usersControllerUpdateResponseTransformer = async (data: any): Promise<UsersControllerUpdateResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

export const usersControllerAssignRolesResponseTransformer = async (data: any): Promise<UsersControllerAssignRolesResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

export const usersControllerAssignPermissionsResponseTransformer = async (data: any): Promise<UsersControllerAssignPermissionsResponse> => {
    data = userDetailDtoSchemaResponseTransformer(data);
    return data;
};

const rolePaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => roleResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const rolesControllerFindAllResponseTransformer = async (data: any): Promise<RolesControllerFindAllResponse> => {
    data = rolePaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const rolesControllerCreateRoleResponseTransformer = async (data: any): Promise<RolesControllerCreateRoleResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const rolesControllerFindOneResponseTransformer = async (data: any): Promise<RolesControllerFindOneResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const rolesControllerUpdateResponseTransformer = async (data: any): Promise<RolesControllerUpdateResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const rolesControllerAssignPermissionsResponseTransformer = async (data: any): Promise<RolesControllerAssignPermissionsResponse> => {
    data = roleResponseDtoSchemaResponseTransformer(data);
    return data;
};

const permissionPaginatedResponseDtoSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => permissionResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const permissionsControllerFindAllResponseTransformer = async (data: any): Promise<PermissionsControllerFindAllResponse> => {
    data = permissionPaginatedResponseDtoSchemaResponseTransformer(data);
    return data;
};

const permissionSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const permissionsControllerCreateResponseTransformer = async (data: any): Promise<PermissionsControllerCreateResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};

export const permissionsControllerFindOneResponseTransformer = async (data: any): Promise<PermissionsControllerFindOneResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};

export const permissionsControllerUpdateResponseTransformer = async (data: any): Promise<PermissionsControllerUpdateResponse> => {
    data = permissionSchemaResponseTransformer(data);
    return data;
};
