// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type LoginDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type TokenResponseDto = {
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * JWT refresh token
     */
    refreshToken: string;
};

export type RegisterDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type UserResponseDto = {
    /**
     * User unique identifier
     */
    id: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User full name
     */
    fullName?: string;
};

export type ActiveDto = {
    /**
     * Email verification token
     */
    token: string;
};

export type ForgotPasswordDto = {
    /**
     * Email address to send password reset link
     */
    email: string;
};

export type MessageResponseDto = {
    /**
     * Response message
     */
    message: string;
};

export type ResetPasswordDto = {
    /**
     * Password reset token
     */
    token: string;
    /**
     * New password
     */
    newPassword: string;
};

export type UserListQueryDto = {
    page?: number;
    limit?: number;
    email?: string;
    role?: string;
};

export type UserPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<UserResponseDto>;
};

export type UserProfileDto = {
    /**
     * Email người dùng
     */
    email: string;
    /**
     * Danh sách role của người dùng
     */
    roles: Array<string>;
    /**
     * Danh sách permission của người dùng
     */
    permissions: Array<string>;
};

export type CreateRoleDto = {
    /**
     * Role name
     */
    name: string;
    /**
     * Role description
     */
    description?: string;
    /**
     * List of permission IDs for the role
     */
    permissions?: Array<string>;
};

export type PermissionResponseDto = {
    /**
     * Permission unique identifier
     */
    id: string;
    /**
     * Permission description
     */
    description?: string;
    /**
     * Permission creation date
     */
    createdAt: Date;
    /**
     * Permission last update date
     */
    updatedAt: Date;
};

export type RoleResponseDto = {
    /**
     * Role unique identifier
     */
    id: string;
    /**
     * Role name
     */
    name: string;
    /**
     * Role description
     */
    description?: string;
    /**
     * Role creation date
     */
    createdAt: Date;
    /**
     * Role last update date
     */
    updatedAt: Date;
    /**
     * Permissions assigned to this role
     */
    permissions?: Array<PermissionResponseDto>;
};

export type UpdateRoleDto = {
    /**
     * Role name
     */
    name?: string;
    /**
     * Role description
     */
    description?: string;
};

export type AssignPermissionsDto = {
    /**
     * Danh sách permission ID
     */
    permissionIds: Array<string>;
};

export type CreatePermissionDto = {
    /**
     * Module
     */
    module: string;
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'assign.role';
    description?: string;
    /**
     * Đánh dấu permission hệ thống
     */
    isSystem?: boolean;
};

export type Permission = {
    /**
     * ID permission
     */
    id: string;
    /**
     * Module
     */
    module: string;
    /**
     * Hành động CRUD
     */
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'assign.role';
    description?: string;
    /**
     * Permission hệ thống (readonly)
     */
    isSystem: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type PermissionMetaResponseDto = {
    /**
     * Danh sách module hiện có
     */
    modules: Array<string>;
    /**
     * Danh sách action hệ thống (CRUD)
     */
    systemActions: Array<string>;
    /**
     * Danh sách action custom (non-system)
     */
    customActions: Array<string>;
};

export type UpdatePermissionDto = {
    description?: string;
};

export type AppControllerHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type AppControllerHealthResponses = {
    200: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginResponses = {
    /**
     * Login successful
     */
    200: TokenResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterResponses = {
    /**
     * User registered successfully
     */
    201: UserResponseDto;
};

export type AuthControllerRegisterResponse = AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerActiveData = {
    body: ActiveDto;
    path?: never;
    query?: never;
    url: '/auth/active';
};

export type AuthControllerActiveResponses = {
    /**
     * Account activated successfully
     */
    200: UserResponseDto;
};

export type AuthControllerActiveResponse = AuthControllerActiveResponses[keyof AuthControllerActiveResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type AuthControllerRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: TokenResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
    /**
     * Password reset email sent if email exists
     */
    200: MessageResponseDto;
};

export type AuthControllerForgotPasswordResponse = AuthControllerForgotPasswordResponses[keyof AuthControllerForgotPasswordResponses];

export type AuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthControllerResetPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: MessageResponseDto;
};

export type AuthControllerResetPasswordResponse = AuthControllerResetPasswordResponses[keyof AuthControllerResetPasswordResponses];

export type AuthControllerGoogleLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google';
};

export type AuthControllerGoogleLoginResponses = {
    200: unknown;
};

export type AuthControllerGoogleCallbackData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/google/callback';
};

export type AuthControllerGoogleCallbackResponses = {
    /**
     * Google login successful
     */
    200: TokenResponseDto;
};

export type AuthControllerGoogleCallbackResponse = AuthControllerGoogleCallbackResponses[keyof AuthControllerGoogleCallbackResponses];

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        email?: string;
        role?: string;
    };
    url: '/users';
};

export type UsersControllerFindAllResponses = {
    200: UserPaginatedResponseDto;
};

export type UsersControllerFindAllResponse = UsersControllerFindAllResponses[keyof UsersControllerFindAllResponses];

export type UsersControllerGetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile';
};

export type UsersControllerGetProfileResponses = {
    200: UserProfileDto;
};

export type UsersControllerGetProfileResponse = UsersControllerGetProfileResponses[keyof UsersControllerGetProfileResponses];

export type RolesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/roles';
};

export type RolesControllerFindAllResponses = {
    200: Array<RoleResponseDto>;
};

export type RolesControllerFindAllResponse = RolesControllerFindAllResponses[keyof RolesControllerFindAllResponses];

export type RolesControllerCreateRoleData = {
    body: CreateRoleDto;
    path?: never;
    query?: never;
    url: '/roles';
};

export type RolesControllerCreateRoleResponses = {
    /**
     * Role created successfully
     */
    201: RoleResponseDto;
};

export type RolesControllerCreateRoleResponse = RolesControllerCreateRoleResponses[keyof RolesControllerCreateRoleResponses];

export type RolesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/roles/{id}';
};

export type RolesControllerRemoveResponses = {
    200: unknown;
};

export type RolesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/roles/{id}';
};

export type RolesControllerFindOneResponses = {
    200: RoleResponseDto;
};

export type RolesControllerFindOneResponse = RolesControllerFindOneResponses[keyof RolesControllerFindOneResponses];

export type RolesControllerUpdateData = {
    body: UpdateRoleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/roles/{id}';
};

export type RolesControllerUpdateResponses = {
    200: RoleResponseDto;
};

export type RolesControllerUpdateResponse = RolesControllerUpdateResponses[keyof RolesControllerUpdateResponses];

export type RolesControllerAssignPermissionsData = {
    body: AssignPermissionsDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/roles/{id}/permissions';
};

export type RolesControllerAssignPermissionsResponses = {
    200: RoleResponseDto;
};

export type RolesControllerAssignPermissionsResponse = RolesControllerAssignPermissionsResponses[keyof RolesControllerAssignPermissionsResponses];

export type PermissionsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
    };
    url: '/permissions';
};

export type PermissionsControllerFindAllResponses = {
    200: Array<Permission>;
};

export type PermissionsControllerFindAllResponse = PermissionsControllerFindAllResponses[keyof PermissionsControllerFindAllResponses];

export type PermissionsControllerCreateData = {
    body: CreatePermissionDto;
    path?: never;
    query?: never;
    url: '/permissions';
};

export type PermissionsControllerCreateResponses = {
    201: Permission;
};

export type PermissionsControllerCreateResponse = PermissionsControllerCreateResponses[keyof PermissionsControllerCreateResponses];

export type PermissionsControllerGetMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/permissions/meta';
};

export type PermissionsControllerGetMetaResponses = {
    200: PermissionMetaResponseDto;
};

export type PermissionsControllerGetMetaResponse = PermissionsControllerGetMetaResponses[keyof PermissionsControllerGetMetaResponses];

export type PermissionsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/permissions/{id}';
};

export type PermissionsControllerRemoveResponses = {
    /**
     * Permission deleted
     */
    200: unknown;
};

export type PermissionsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/permissions/{id}';
};

export type PermissionsControllerFindOneResponses = {
    200: Permission;
};

export type PermissionsControllerFindOneResponse = PermissionsControllerFindOneResponses[keyof PermissionsControllerFindOneResponses];

export type PermissionsControllerUpdateData = {
    body: UpdatePermissionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/permissions/{id}';
};

export type PermissionsControllerUpdateResponses = {
    200: Permission;
};

export type PermissionsControllerUpdateResponse = PermissionsControllerUpdateResponses[keyof PermissionsControllerUpdateResponses];
