// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

export type LoginDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type TokenResponseDto = {
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * JWT refresh token
     */
    refreshToken: string;
};

export type RegisterDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type MessageResponseDto = {
    /**
     * Response message
     */
    message: string;
};

export type ActiveDto = {
    /**
     * Email verification token
     */
    token: string;
};

export type UserInformationResponseDto = {
    /**
     * User unique identifier
     */
    id: string;
    /**
     * User email address
     */
    email: string;
    /**
     * User full name
     */
    fullName?: string;
};

export type ForgotPasswordDto = {
    /**
     * Email address to send password reset link
     */
    email: string;
};

export type ResetPasswordDto = {
    /**
     * Password reset token
     */
    token: string;
    /**
     * New password
     */
    newPassword: string;
};

export type UserProfileDto = {
    /**
     * ID người dùng
     */
    id: string;
    /**
     * Tên người dùng
     */
    name: string;
    /**
     * Email người dùng
     */
    email: string;
    /**
     * Danh sách role của người dùng
     */
    roles: Array<string>;
    /**
     * Danh sách permission của người dùng
     */
    permissions: Array<string>;
};

export type UserListQueryDto = {
    page?: number;
    limit?: number;
    email?: string;
    role?: string;
    userCode?: string;
};

export type PermissionResponseDto = {
    id: string;
    module: string;
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'assign.role';
    description: string;
    isSystem: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type RoleResponseDto = {
    /**
     * Role unique identifier
     */
    id: string;
    /**
     * Role name
     */
    name: string;
    /**
     * Role description
     */
    description?: string;
    /**
     * Role creation date
     */
    createdAt: Date;
    /**
     * Role last update date
     */
    updatedAt: Date;
    /**
     * Permissions assigned to this role
     */
    permissions?: Array<PermissionResponseDto>;
};

export type UserResponseDto = {
    /**
     * User ID
     */
    id: string;
    userCode: string;
    email: string;
    fullName: string;
    /**
     * Roles to assign to the user
     */
    roles: Array<RoleResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type UserPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<UserResponseDto>;
};

export type UserDetailDto = {
    id: string;
    userCode: string;
    email: string;
    fullName: string | null;
    avatar: string | null;
    roles: Array<RoleResponseDto>;
    /**
     * Direct permissions
     */
    permissions: Array<PermissionResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type AssignRolesDto = {
    /**
     * Danh sách role ID
     */
    roleIds: Array<string>;
};

export type AssignUserPermissionsDto = {
    /**
     * Danh sách permission ID gán trực tiếp cho user
     */
    permissionIds: Array<string>;
};

export type CreateRoleDto = {
    /**
     * Role name
     */
    name: string;
    /**
     * Role description
     */
    description?: string;
    /**
     * List of permission IDs for the role
     */
    permissions?: Array<string>;
};

export type RolePaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<RoleResponseDto>;
};

export type UpdateRoleDto = {
    /**
     * Role name
     */
    name?: string;
    /**
     * Role description
     */
    description?: string;
};

export type AssignPermissionsDto = {
    /**
     * Danh sách permission ID
     */
    permissionIds: Array<string>;
};

export type CreatePermissionDto = {
    /**
     * Module
     */
    module: string;
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'assign.role';
    description?: string;
    /**
     * Đánh dấu permission hệ thống
     */
    isSystem?: boolean;
};

export type Permission = {
    /**
     * ID
     */
    id: string;
    /**
     * Thời gian tạo
     */
    createdAt: Date;
    /**
     * Thời gian cập nhật
     */
    updatedAt: Date;
    /**
     * Module
     */
    module: string;
    /**
     * Hành động CRUD
     */
    action: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'assign.role';
    description?: string;
    /**
     * Permission hệ thống (readonly)
     */
    isSystem: boolean;
};

export type PermissionMetaResponseDto = {
    /**
     * Danh sách module hiện có
     */
    modules: Array<string>;
    /**
     * Danh sách action hệ thống (CRUD)
     */
    systemActions: Array<string>;
    /**
     * Danh sách action custom (non-system)
     */
    customActions: Array<string>;
};

export type PermissionPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<PermissionResponseDto>;
};

export type UpdatePermissionDto = {
    description?: string;
};

export type CategoryResponseDto = {
    id: string;
    parent_id?: {
        [key: string]: unknown;
    } | null;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    image?: {
        [key: string]: unknown;
    } | null;
    sortOrder: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type CategoryPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<CategoryResponseDto>;
};

export type CategoryTreeNodeDto = {
    id: string;
    parent_id?: {
        [key: string]: unknown;
    } | null;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    image?: {
        [key: string]: unknown;
    } | null;
    sortOrder: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
    children?: Array<CategoryTreeNodeDto>;
};

export type AdminCategoryResponseDto = {
    id: string;
    parent_id?: {
        [key: string]: unknown;
    } | null;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    image?: {
        [key: string]: unknown;
    } | null;
    sortOrder: number;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateCategoryDto = {
    /**
     * Category name
     */
    name: string;
    /**
     * SEO slug (auto-generated from name if omitted)
     */
    slug?: string;
    /**
     * Parent category ID
     */
    parent_id?: string;
    description?: string;
    image?: string;
    sortOrder?: number;
    isActive?: boolean;
};

export type UpdateCategoryDto = {
    /**
     * Category name
     */
    name?: string;
    /**
     * SEO slug (auto-generated from name if omitted)
     */
    slug?: string;
    /**
     * Parent category ID
     */
    parent_id?: string;
    description?: string;
    image?: string;
    sortOrder?: number;
    isActive?: boolean;
};

export type UploadResultDto = {
    url: string;
    publicId: string;
    width?: number;
    height?: number;
    format?: string;
    bytes?: number;
    originalName: string;
};

export type MultiUploadResultDto = {
    files: Array<UploadResultDto>;
};

export type ProductListItemDto = {
    id: string;
    category_id: string;
    name: string;
    slug: string;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type ProductPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<ProductListItemDto>;
};

export type ProductImageResponseDto = {
    id: string;
    variant_id?: {
        [key: string]: unknown;
    } | null;
    url: string;
    alt?: {
        [key: string]: unknown;
    } | null;
    isPrimary: boolean;
    sortOrder: number;
};

export type ProductVariantResponseDto = {
    id: string;
    name: string;
    sku: string;
    price: number;
    stock: number;
    attributes?: {
        [key: string]: unknown;
    } | null;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type TagResponseDto = {
    id: string;
    name: string;
    slug: string;
};

export type ProductResponseDto = {
    id: string;
    category_id: string;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    images: Array<ProductImageResponseDto>;
    variants: Array<ProductVariantResponseDto>;
    tags: Array<TagResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type AdminProductResponseDto = {
    id: string;
    category_id: string;
    name: string;
    slug: string;
    description?: {
        [key: string]: unknown;
    } | null;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    images: Array<ProductImageResponseDto>;
    variants: Array<ProductVariantResponseDto>;
    tags: Array<TagResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateProductImageDto = {
    url: string;
    variant_id?: string;
    alt?: string;
    isPrimary?: boolean;
    sortOrder?: number;
};

export type CreateProductVariantDto = {
    name: string;
    sku: string;
    price: number;
    stock?: number;
    attributes?: {
        [key: string]: unknown;
    };
    isActive?: boolean;
};

export type CreateProductDto = {
    category_id: string;
    name: string;
    /**
     * Auto-generated from name if omitted
     */
    slug?: string;
    description?: string;
    basePrice: number;
    sku: string;
    status?: 'draft' | 'published' | 'archived';
    isFeatured?: boolean;
    images?: Array<CreateProductImageDto>;
    variants?: Array<CreateProductVariantDto>;
    tagIds?: Array<string>;
};

export type UpdateProductDto = {
    category_id?: string;
    name?: string;
    /**
     * Auto-generated from name if omitted
     */
    slug?: string;
    description?: string;
    basePrice?: number;
    sku?: string;
    status?: 'draft' | 'published' | 'archived';
    isFeatured?: boolean;
    images?: Array<CreateProductImageDto>;
    variants?: Array<CreateProductVariantDto>;
    tagIds?: Array<string>;
};

export type UpdateProductVariantDto = {
    name?: string;
    sku?: string;
    price?: number;
    stock?: number;
    attributes?: {
        [key: string]: unknown;
    };
    isActive?: boolean;
};

export type CreateTagDto = {
    name: string;
    /**
     * Auto-generated from name if omitted
     */
    slug?: string;
};

export type AdminTagResponseDto = {
    id: string;
    name: string;
    slug: string;
};

export type AddressResponseDto = {
    id: string;
    fullName: string;
    phone: string;
    addressLine1: string;
    addressLine2?: {
        [key: string]: unknown;
    };
    city: string;
    province: string;
    country: string;
    postalCode?: {
        [key: string]: unknown;
    };
    isDefault: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateAddressDto = {
    fullName: string;
    phone: string;
    addressLine1: string;
    addressLine2?: string;
    city: string;
    province: string;
    country?: string;
    postalCode?: string;
    isDefault?: boolean;
};

export type UpdateAddressDto = {
    fullName?: string;
    phone?: string;
    addressLine1?: string;
    addressLine2?: string;
    city?: string;
    province?: string;
    country?: string;
    postalCode?: string;
    isDefault?: boolean;
};

export type CreateOrderItemDto = {
    /**
     * Product variant ID
     */
    variant_id: string;
    quantity: number;
};

export type CreateOrderDto = {
    /**
     * Delivery address ID
     */
    address_id: string;
    items: Array<CreateOrderItemDto>;
    /**
     * Discount coupon code
     */
    discountCode?: string;
    notes?: string;
};

export type OrderItemResponseDto = {
    id: string;
    order_id: string;
    variant_id?: {
        [key: string]: unknown;
    };
    productName: string;
    variantName?: {
        [key: string]: unknown;
    };
    unitPrice: number;
    quantity: number;
    total: number;
};

export type AppliedDiscountDto = {
    id: string;
    code: string;
    type: 'percent' | 'fixed';
    value: number;
};

export type OrderResponseDto = {
    id: string;
    user_id: string;
    address_id?: {
        [key: string]: unknown;
    };
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
    subtotal: number;
    shippingFee: number;
    discount: number;
    total: number;
    notes?: {
        [key: string]: unknown;
    };
    items: Array<OrderItemResponseDto>;
    discounts: Array<AppliedDiscountDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type OrderListItemDto = {
    id: string;
    user_id: string;
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
    total: number;
    createdAt: Date;
};

export type OrderPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<OrderListItemDto>;
};

export type AdminOrderListItemDto = {
    id: string;
    user_id: string;
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
    total: number;
    createdAt: Date;
};

export type AdminOrderPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminOrderListItemDto>;
};

export type AdminOrderResponseDto = {
    id: string;
    user_id: string;
    address_id?: {
        [key: string]: unknown;
    };
    orderNumber: string;
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
    subtotal: number;
    shippingFee: number;
    discount: number;
    total: number;
    notes?: {
        [key: string]: unknown;
    };
    items: Array<OrderItemResponseDto>;
    discounts: Array<AppliedDiscountDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type UpdateOrderStatusDto = {
    status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
};

export type ValidateDiscountDto = {
    code: string;
    /**
     * Order subtotal to calculate discount against
     */
    subtotal: number;
};

export type ValidateDiscountResponseDto = {
    discountId: string;
    code: string;
    type: 'percent' | 'fixed';
    value: number;
    /**
     * Computed discount amount in VND
     */
    discountAmount: number;
};

export type CreateDiscountDto = {
    code: string;
    type: 'percent' | 'fixed';
    /**
     * Percent (0–100) or fixed amount in VND
     */
    value: number;
    /**
     * Minimum subtotal to apply
     */
    minOrderValue?: number;
    /**
     * Max total usages (null = unlimited)
     */
    usageLimit?: number;
    isActive?: boolean;
    startsAt?: Date;
    expiresAt?: Date;
};

export type AdminDiscountResponseDto = {
    id: string;
    code: string;
    type: 'percent' | 'fixed';
    value: number;
    minOrderValue?: {
        [key: string]: unknown;
    };
    usageLimit?: {
        [key: string]: unknown;
    };
    usedCount: number;
    isActive: boolean;
    startsAt?: {
        [key: string]: unknown;
    };
    expiresAt?: {
        [key: string]: unknown;
    };
    createdAt: Date;
    updatedAt: Date;
};

export type AdminDiscountPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminDiscountResponseDto>;
};

export type UpdateDiscountDto = {
    code?: string;
    type?: 'percent' | 'fixed';
    /**
     * Percent (0–100) or fixed amount in VND
     */
    value?: number;
    /**
     * Minimum subtotal to apply
     */
    minOrderValue?: number;
    /**
     * Max total usages (null = unlimited)
     */
    usageLimit?: number;
    isActive?: boolean;
    startsAt?: Date;
    expiresAt?: Date;
};

export type CreatePaymentDto = {
    /**
     * Order ID to pay for
     */
    order_id: string;
    method: 'cod' | 'vnpay' | 'momo' | 'zalopay' | 'stripe' | 'bank_transfer';
};

export type PaymentResponseDto = {
    id: string;
    order_id: string;
    method: 'cod' | 'vnpay' | 'momo' | 'zalopay' | 'stripe' | 'bank_transfer';
    status: 'pending' | 'completed' | 'failed' | 'refunded';
    amount: number;
    transactionId?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
    paidAt?: {
        [key: string]: unknown;
    };
    createdAt: Date;
    updatedAt: Date;
};

export type PaymentPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<PaymentResponseDto>;
};

export type AdminPaymentResponseDto = {
    id: string;
    order_id: string;
    method: 'cod' | 'vnpay' | 'momo' | 'zalopay' | 'stripe' | 'bank_transfer';
    status: 'pending' | 'completed' | 'failed' | 'refunded';
    amount: number;
    transactionId?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
    paidAt?: {
        [key: string]: unknown;
    };
    createdAt: Date;
    updatedAt: Date;
};

export type AdminPaymentPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminPaymentResponseDto>;
};

export type UpdatePaymentStatusDto = {
    status: 'pending' | 'completed' | 'failed' | 'refunded';
    transactionId?: string;
    /**
     * Raw response from payment gateway
     */
    metadata?: {
        [key: string]: unknown;
    };
};

export type CartItemVariantDto = {
    id: string;
    name: string;
    sku: string;
    price: number;
    stock: number;
    attributes?: {
        [key: string]: unknown;
    };
};

export type CartItemResponseDto = {
    id: string;
    cart_id: string;
    variant_id: string;
    variant: CartItemVariantDto;
    quantity: number;
    createdAt: Date;
    updatedAt: Date;
};

export type CartResponseDto = {
    id: string;
    user_id: string;
    items: Array<CartItemResponseDto>;
    createdAt: Date;
    updatedAt: Date;
};

export type AddCartItemDto = {
    variant_id: string;
    quantity?: number;
};

export type UpdateCartItemDto = {
    /**
     * New quantity (min 1)
     */
    quantity: number;
};

export type CreateReviewDto = {
    /**
     * Product to review
     */
    product_id: string;
    rating: number;
    title?: string;
    content?: string;
};

export type ReviewAuthorDto = {
    id: string;
    fullName?: {
        [key: string]: unknown;
    } | null;
    avatar?: {
        [key: string]: unknown;
    } | null;
};

export type ReviewResponseDto = {
    id: string;
    user_id: string;
    user: ReviewAuthorDto;
    product_id: string;
    rating: number;
    title?: {
        [key: string]: unknown;
    } | null;
    content?: {
        [key: string]: unknown;
    } | null;
    isVerified: boolean;
    isApproved: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type ReviewPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<ReviewResponseDto>;
};

export type UpdateReviewDto = {
    rating?: number;
    title?: string;
    content?: string;
};

export type AdminReviewResponseDto = {
    id: string;
    user_id: string;
    user: ReviewAuthorDto;
    product_id: string;
    rating: number;
    title?: {
        [key: string]: unknown;
    } | null;
    content?: {
        [key: string]: unknown;
    } | null;
    isVerified: boolean;
    isApproved: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type AdminReviewPaginatedResponseDto = {
    total: number;
    page: number;
    limit: number;
    data: Array<AdminReviewResponseDto>;
};

export type WishlistProductDto = {
    id: string;
    name: string;
    slug: string;
    basePrice: number;
    sku: string;
    status: 'draft' | 'published' | 'archived';
    isFeatured: boolean;
    description?: {
        [key: string]: unknown;
    } | null;
};

export type WishlistItemResponseDto = {
    id: string;
    product_id: string;
    product: WishlistProductDto;
    createdAt: Date;
};

export type WishlistResponseDto = {
    items: Array<WishlistItemResponseDto>;
    total: number;
};

export type AddToWishlistDto = {
    /**
     * Product ID to add
     */
    product_id: string;
};

export type BannerResponseDto = {
    id: string;
    title: string;
    subtitle?: {
        [key: string]: unknown;
    };
    position: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl: string;
    imageMobileUrl?: {
        [key: string]: unknown;
    };
    linkType: 'url' | 'product' | 'category' | 'discount';
    linkValue?: {
        [key: string]: unknown;
    };
    sortOrder: number;
    isActive: boolean;
    startsAt?: {
        [key: string]: unknown;
    };
    endsAt?: {
        [key: string]: unknown;
    };
    clickCount: number;
    createdAt: Date;
    updatedAt: Date;
};

export type AdminBannerResponseDto = {
    id: string;
    title: string;
    subtitle?: {
        [key: string]: unknown;
    };
    position: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl: string;
    imageMobileUrl?: {
        [key: string]: unknown;
    };
    linkType: 'url' | 'product' | 'category' | 'discount';
    linkValue?: {
        [key: string]: unknown;
    };
    sortOrder: number;
    isActive: boolean;
    startsAt?: {
        [key: string]: unknown;
    };
    endsAt?: {
        [key: string]: unknown;
    };
    clickCount: number;
    createdAt: Date;
    updatedAt: Date;
};

export type CreateBannerDto = {
    title: string;
    subtitle?: string;
    position: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl: string;
    imageMobileUrl?: string;
    imagePublicId?: string;
    imageMobilePublicId?: string;
    linkType: 'url' | 'product' | 'category' | 'discount';
    linkValue?: string;
    sortOrder?: number;
    isActive?: boolean;
    startsAt?: Date;
    endsAt?: Date;
};

export type BannerOrderItemDto = {
    id: string;
    sortOrder: number;
};

export type ReorderBannersDto = {
    items: Array<BannerOrderItemDto>;
};

export type UpdateBannerDto = {
    title?: string;
    subtitle?: string;
    position?: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    imageUrl?: string;
    imageMobileUrl?: string;
    imagePublicId?: string;
    imageMobilePublicId?: string;
    linkType?: 'url' | 'product' | 'category' | 'discount';
    linkValue?: string;
    sortOrder?: number;
    isActive?: boolean;
    startsAt?: Date;
    endsAt?: Date;
};

export type AdminAuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/admin/auth/login';
};

export type AdminAuthControllerLoginResponses = {
    /**
     * Đăng nhập thành công
     */
    200: TokenResponseDto;
};

export type AdminAuthControllerLoginResponse = AdminAuthControllerLoginResponses[keyof AdminAuthControllerLoginResponses];

export type AdminAuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/auth/me';
};

export type AdminAuthControllerMeResponses = {
    /**
     * Current admin profile
     */
    200: UserProfileDto;
};

export type AdminAuthControllerMeResponse = AdminAuthControllerMeResponses[keyof AdminAuthControllerMeResponses];

export type AdminAuthControllerActiveData = {
    body: ActiveDto;
    path?: never;
    query?: never;
    url: '/admin/auth/active';
};

export type AdminAuthControllerActiveResponses = {
    /**
     * Account activated successfully
     */
    200: UserInformationResponseDto;
};

export type AdminAuthControllerActiveResponse = AdminAuthControllerActiveResponses[keyof AdminAuthControllerActiveResponses];

export type AdminAuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/auth/refresh';
};

export type AdminAuthControllerRefreshResponses = {
    /**
     * Token refreshed successfully
     */
    200: TokenResponseDto;
};

export type AdminAuthControllerRefreshResponse = AdminAuthControllerRefreshResponses[keyof AdminAuthControllerRefreshResponses];

export type AdminAuthControllerForgotPasswordData = {
    body: ForgotPasswordDto;
    path?: never;
    query?: never;
    url: '/admin/auth/forgot-password';
};

export type AdminAuthControllerForgotPasswordResponses = {
    /**
     * Password reset email sent if email exists
     */
    200: MessageResponseDto;
};

export type AdminAuthControllerForgotPasswordResponse = AdminAuthControllerForgotPasswordResponses[keyof AdminAuthControllerForgotPasswordResponses];

export type AdminAuthControllerResetPasswordData = {
    body: ResetPasswordDto;
    path?: never;
    query?: never;
    url: '/admin/auth/reset-password';
};

export type AdminAuthControllerResetPasswordResponses = {
    /**
     * Password reset successfully
     */
    200: MessageResponseDto;
};

export type AdminAuthControllerResetPasswordResponse = AdminAuthControllerResetPasswordResponses[keyof AdminAuthControllerResetPasswordResponses];

export type AdminUsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        email?: string;
        role?: string;
        userCode?: string;
    };
    url: '/admin/users';
};

export type AdminUsersControllerFindAllResponses = {
    200: UserPaginatedResponseDto;
};

export type AdminUsersControllerFindAllResponse = AdminUsersControllerFindAllResponses[keyof AdminUsersControllerFindAllResponses];

export type AdminUsersControllerFindByUserCodeData = {
    body?: never;
    path: {
        userCode: string;
    };
    query?: never;
    url: '/admin/users/by-code/{userCode}';
};

export type AdminUsersControllerFindByUserCodeResponses = {
    200: UserDetailDto;
};

export type AdminUsersControllerFindByUserCodeResponse = AdminUsersControllerFindByUserCodeResponses[keyof AdminUsersControllerFindByUserCodeResponses];

export type AdminUsersControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerRemoveResponses = {
    /**
     * User deleted
     */
    204: void;
};

export type AdminUsersControllerRemoveResponse = AdminUsersControllerRemoveResponses[keyof AdminUsersControllerRemoveResponses];

export type AdminUsersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerFindOneResponses = {
    200: UserDetailDto;
};

export type AdminUsersControllerFindOneResponse = AdminUsersControllerFindOneResponses[keyof AdminUsersControllerFindOneResponses];

export type AdminUsersControllerUpdateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}';
};

export type AdminUsersControllerUpdateResponses = {
    200: UserDetailDto;
};

export type AdminUsersControllerUpdateResponse = AdminUsersControllerUpdateResponses[keyof AdminUsersControllerUpdateResponses];

export type AdminUsersControllerAssignRolesData = {
    body: AssignRolesDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/roles';
};

export type AdminUsersControllerAssignRolesResponses = {
    200: UserDetailDto;
};

export type AdminUsersControllerAssignRolesResponse = AdminUsersControllerAssignRolesResponses[keyof AdminUsersControllerAssignRolesResponses];

export type AdminUsersControllerAssignPermissionsData = {
    body: AssignUserPermissionsDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/users/{id}/permissions';
};

export type AdminUsersControllerAssignPermissionsResponses = {
    200: UserDetailDto;
};

export type AdminUsersControllerAssignPermissionsResponse = AdminUsersControllerAssignPermissionsResponses[keyof AdminUsersControllerAssignPermissionsResponses];

export type AdminRolesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Filter by role name
         */
        name?: string;
    };
    url: '/admin/roles';
};

export type AdminRolesControllerFindAllResponses = {
    200: RolePaginatedResponseDto;
};

export type AdminRolesControllerFindAllResponse = AdminRolesControllerFindAllResponses[keyof AdminRolesControllerFindAllResponses];

export type AdminRolesControllerCreateRoleData = {
    body: CreateRoleDto;
    path?: never;
    query?: never;
    url: '/admin/roles';
};

export type AdminRolesControllerCreateRoleResponses = {
    /**
     * Role created successfully
     */
    201: RoleResponseDto;
};

export type AdminRolesControllerCreateRoleResponse = AdminRolesControllerCreateRoleResponses[keyof AdminRolesControllerCreateRoleResponses];

export type AdminRolesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/roles/{id}';
};

export type AdminRolesControllerRemoveResponses = {
    200: unknown;
};

export type AdminRolesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/roles/{id}';
};

export type AdminRolesControllerFindOneResponses = {
    200: RoleResponseDto;
};

export type AdminRolesControllerFindOneResponse = AdminRolesControllerFindOneResponses[keyof AdminRolesControllerFindOneResponses];

export type AdminRolesControllerUpdateData = {
    body: UpdateRoleDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/roles/{id}';
};

export type AdminRolesControllerUpdateResponses = {
    200: RoleResponseDto;
};

export type AdminRolesControllerUpdateResponse = AdminRolesControllerUpdateResponses[keyof AdminRolesControllerUpdateResponses];

export type AdminRolesControllerAssignPermissionsData = {
    body: AssignPermissionsDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/roles/{id}/permissions';
};

export type AdminRolesControllerAssignPermissionsResponses = {
    200: RoleResponseDto;
};

export type AdminRolesControllerAssignPermissionsResponse = AdminRolesControllerAssignPermissionsResponses[keyof AdminRolesControllerAssignPermissionsResponses];

export type AdminPermissionsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Filter by module name
         */
        module?: string;
        /**
         * Filter by action
         */
        action?: 'create' | 'read' | 'update' | 'delete' | 'cancel' | 'publish' | 'assign.role';
    };
    url: '/admin/permissions';
};

export type AdminPermissionsControllerFindAllResponses = {
    200: PermissionPaginatedResponseDto;
};

export type AdminPermissionsControllerFindAllResponse = AdminPermissionsControllerFindAllResponses[keyof AdminPermissionsControllerFindAllResponses];

export type AdminPermissionsControllerCreateData = {
    body: CreatePermissionDto;
    path?: never;
    query?: never;
    url: '/admin/permissions';
};

export type AdminPermissionsControllerCreateResponses = {
    201: Permission;
};

export type AdminPermissionsControllerCreateResponse = AdminPermissionsControllerCreateResponses[keyof AdminPermissionsControllerCreateResponses];

export type AdminPermissionsControllerGetMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/permissions/meta';
};

export type AdminPermissionsControllerGetMetaResponses = {
    200: PermissionMetaResponseDto;
};

export type AdminPermissionsControllerGetMetaResponse = AdminPermissionsControllerGetMetaResponses[keyof AdminPermissionsControllerGetMetaResponses];

export type AdminPermissionsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/permissions/{id}';
};

export type AdminPermissionsControllerRemoveResponses = {
    /**
     * Permission deleted
     */
    200: unknown;
};

export type AdminPermissionsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/permissions/{id}';
};

export type AdminPermissionsControllerFindOneResponses = {
    200: Permission;
};

export type AdminPermissionsControllerFindOneResponse = AdminPermissionsControllerFindOneResponses[keyof AdminPermissionsControllerFindOneResponses];

export type AdminPermissionsControllerUpdateData = {
    body: UpdatePermissionDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/permissions/{id}';
};

export type AdminPermissionsControllerUpdateResponses = {
    200: Permission;
};

export type AdminPermissionsControllerUpdateResponse = AdminPermissionsControllerUpdateResponses[keyof AdminPermissionsControllerUpdateResponses];

export type AdminCategoriesControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Filter by category name
         */
        name?: string;
        /**
         * Filter by parent category ID (omit for all, use null for root)
         */
        parent_id?: string;
        /**
         * Filter by active status
         */
        isActive?: boolean;
    };
    url: '/admin/categories';
};

export type AdminCategoriesControllerFindAllResponses = {
    200: CategoryPaginatedResponseDto;
};

export type AdminCategoriesControllerFindAllResponse = AdminCategoriesControllerFindAllResponses[keyof AdminCategoriesControllerFindAllResponses];

export type AdminCategoriesControllerCreateData = {
    body: CreateCategoryDto;
    path?: never;
    query?: never;
    url: '/admin/categories';
};

export type AdminCategoriesControllerCreateResponses = {
    201: AdminCategoryResponseDto;
};

export type AdminCategoriesControllerCreateResponse = AdminCategoriesControllerCreateResponses[keyof AdminCategoriesControllerCreateResponses];

export type AdminCategoriesControllerFindTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/categories/tree';
};

export type AdminCategoriesControllerFindTreeResponses = {
    200: Array<CategoryTreeNodeDto>;
};

export type AdminCategoriesControllerFindTreeResponse = AdminCategoriesControllerFindTreeResponses[keyof AdminCategoriesControllerFindTreeResponses];

export type AdminCategoriesControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/categories/{id}';
};

export type AdminCategoriesControllerRemoveResponses = {
    200: unknown;
};

export type AdminCategoriesControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/categories/{id}';
};

export type AdminCategoriesControllerFindOneResponses = {
    200: AdminCategoryResponseDto;
};

export type AdminCategoriesControllerFindOneResponse = AdminCategoriesControllerFindOneResponses[keyof AdminCategoriesControllerFindOneResponses];

export type AdminCategoriesControllerUpdateData = {
    body: UpdateCategoryDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/categories/{id}';
};

export type AdminCategoriesControllerUpdateResponses = {
    200: AdminCategoryResponseDto;
};

export type AdminCategoriesControllerUpdateResponse = AdminCategoriesControllerUpdateResponses[keyof AdminCategoriesControllerUpdateResponses];

export type AdminCategoriesControllerUploadImageData = {
    body: {
        file: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/categories/{id}/image/upload';
};

export type AdminCategoriesControllerUploadImageResponses = {
    200: AdminCategoryResponseDto;
};

export type AdminCategoriesControllerUploadImageResponse = AdminCategoriesControllerUploadImageResponses[keyof AdminCategoriesControllerUploadImageResponses];

export type AdminCategoriesControllerRemoveImageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/categories/{id}/image';
};

export type AdminCategoriesControllerRemoveImageResponses = {
    200: AdminCategoryResponseDto;
};

export type AdminCategoriesControllerRemoveImageResponse = AdminCategoriesControllerRemoveImageResponses[keyof AdminCategoriesControllerRemoveImageResponses];

export type AdminMediaControllerUploadOneData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/admin/media/upload';
};

export type AdminMediaControllerUploadOneResponses = {
    201: UploadResultDto;
};

export type AdminMediaControllerUploadOneResponse = AdminMediaControllerUploadOneResponses[keyof AdminMediaControllerUploadOneResponses];

export type AdminMediaControllerUploadManyData = {
    body: {
        files: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/admin/media/upload/multiple';
};

export type AdminMediaControllerUploadManyResponses = {
    200: MultiUploadResultDto;
};

export type AdminMediaControllerUploadManyResponse = AdminMediaControllerUploadManyResponses[keyof AdminMediaControllerUploadManyResponses];

export type AdminMediaControllerRemoveData = {
    body?: never;
    path: {
        /**
         * Provider public ID (may contain slashes)
         */
        publicId: string;
    };
    query?: never;
    url: '/admin/media/{publicId}';
};

export type AdminMediaControllerRemoveResponses = {
    200: unknown;
};

export type AdminProductsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Filter by product name
         */
        name?: string;
        /**
         * Filter by category ID
         */
        category_id?: string;
        status?: 'draft' | 'published' | 'archived';
        /**
         * Filter featured products
         */
        isFeatured?: boolean;
    };
    url: '/admin/products';
};

export type AdminProductsControllerFindAllResponses = {
    200: ProductPaginatedResponseDto;
};

export type AdminProductsControllerFindAllResponse = AdminProductsControllerFindAllResponses[keyof AdminProductsControllerFindAllResponses];

export type AdminProductsControllerCreateData = {
    body: CreateProductDto;
    path?: never;
    query?: never;
    url: '/admin/products';
};

export type AdminProductsControllerCreateResponses = {
    201: AdminProductResponseDto;
};

export type AdminProductsControllerCreateResponse = AdminProductsControllerCreateResponses[keyof AdminProductsControllerCreateResponses];

export type AdminProductsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/products/{id}';
};

export type AdminProductsControllerRemoveResponses = {
    200: unknown;
};

export type AdminProductsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/products/{id}';
};

export type AdminProductsControllerFindOneResponses = {
    200: AdminProductResponseDto;
};

export type AdminProductsControllerFindOneResponse = AdminProductsControllerFindOneResponses[keyof AdminProductsControllerFindOneResponses];

export type AdminProductsControllerUpdateData = {
    body: UpdateProductDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/products/{id}';
};

export type AdminProductsControllerUpdateResponses = {
    200: AdminProductResponseDto;
};

export type AdminProductsControllerUpdateResponse = AdminProductsControllerUpdateResponses[keyof AdminProductsControllerUpdateResponses];

export type AdminProductsControllerAddImageData = {
    body: CreateProductImageDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/products/{id}/images';
};

export type AdminProductsControllerAddImageResponses = {
    201: ProductImageResponseDto;
};

export type AdminProductsControllerAddImageResponse = AdminProductsControllerAddImageResponses[keyof AdminProductsControllerAddImageResponses];

export type AdminProductsControllerUploadImageData = {
    body: {
        file: Blob | File;
        alt?: string;
        isPrimary?: boolean;
        sortOrder?: number;
        variant_id?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/products/{id}/images/upload';
};

export type AdminProductsControllerUploadImageResponses = {
    201: ProductImageResponseDto;
};

export type AdminProductsControllerUploadImageResponse = AdminProductsControllerUploadImageResponses[keyof AdminProductsControllerUploadImageResponses];

export type AdminProductsControllerRemoveImageData = {
    body?: never;
    path: {
        id: string;
        imageId: string;
    };
    query?: never;
    url: '/admin/products/{id}/images/{imageId}';
};

export type AdminProductsControllerRemoveImageResponses = {
    200: unknown;
};

export type AdminProductsControllerAddVariantData = {
    body: CreateProductVariantDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/products/{id}/variants';
};

export type AdminProductsControllerAddVariantResponses = {
    201: ProductVariantResponseDto;
};

export type AdminProductsControllerAddVariantResponse = AdminProductsControllerAddVariantResponses[keyof AdminProductsControllerAddVariantResponses];

export type AdminProductsControllerRemoveVariantData = {
    body?: never;
    path: {
        id: string;
        variantId: string;
    };
    query?: never;
    url: '/admin/products/{id}/variants/{variantId}';
};

export type AdminProductsControllerRemoveVariantResponses = {
    200: unknown;
};

export type AdminProductsControllerUpdateVariantData = {
    body: UpdateProductVariantDto;
    path: {
        id: string;
        variantId: string;
    };
    query?: never;
    url: '/admin/products/{id}/variants/{variantId}';
};

export type AdminProductsControllerUpdateVariantResponses = {
    200: ProductVariantResponseDto;
};

export type AdminProductsControllerUpdateVariantResponse = AdminProductsControllerUpdateVariantResponses[keyof AdminProductsControllerUpdateVariantResponses];

export type AdminTagsControllerCreateTagData = {
    body: CreateTagDto;
    path?: never;
    query?: never;
    url: '/admin/tags';
};

export type AdminTagsControllerCreateTagResponses = {
    201: AdminTagResponseDto;
};

export type AdminTagsControllerCreateTagResponse = AdminTagsControllerCreateTagResponses[keyof AdminTagsControllerCreateTagResponses];

export type AdminTagsControllerRemoveTagData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/tags/{id}';
};

export type AdminTagsControllerRemoveTagResponses = {
    200: unknown;
};

export type AdminOrdersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        status?: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
        /**
         * Filter by user ID (admin only)
         */
        user_id?: string;
    };
    url: '/admin/orders';
};

export type AdminOrdersControllerFindAllResponses = {
    200: AdminOrderPaginatedResponseDto;
};

export type AdminOrdersControllerFindAllResponse = AdminOrdersControllerFindAllResponses[keyof AdminOrdersControllerFindAllResponses];

export type AdminOrdersControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/orders/{id}';
};

export type AdminOrdersControllerFindOneResponses = {
    200: AdminOrderResponseDto;
};

export type AdminOrdersControllerFindOneResponse = AdminOrdersControllerFindOneResponses[keyof AdminOrdersControllerFindOneResponses];

export type AdminOrdersControllerUpdateStatusData = {
    body: UpdateOrderStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/orders/{id}/status';
};

export type AdminOrdersControllerUpdateStatusResponses = {
    200: AdminOrderResponseDto;
};

export type AdminOrdersControllerUpdateStatusResponse = AdminOrdersControllerUpdateStatusResponses[keyof AdminOrdersControllerUpdateStatusResponses];

export type AdminDiscountsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        search?: string;
        isActive?: boolean;
    };
    url: '/admin/discounts';
};

export type AdminDiscountsControllerFindAllResponses = {
    200: AdminDiscountPaginatedResponseDto;
};

export type AdminDiscountsControllerFindAllResponse = AdminDiscountsControllerFindAllResponses[keyof AdminDiscountsControllerFindAllResponses];

export type AdminDiscountsControllerCreateData = {
    body: CreateDiscountDto;
    path?: never;
    query?: never;
    url: '/admin/discounts';
};

export type AdminDiscountsControllerCreateResponses = {
    201: AdminDiscountResponseDto;
};

export type AdminDiscountsControllerCreateResponse = AdminDiscountsControllerCreateResponses[keyof AdminDiscountsControllerCreateResponses];

export type AdminDiscountsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/discounts/{id}';
};

export type AdminDiscountsControllerRemoveResponses = {
    204: void;
};

export type AdminDiscountsControllerRemoveResponse = AdminDiscountsControllerRemoveResponses[keyof AdminDiscountsControllerRemoveResponses];

export type AdminDiscountsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/discounts/{id}';
};

export type AdminDiscountsControllerFindOneResponses = {
    200: AdminDiscountResponseDto;
};

export type AdminDiscountsControllerFindOneResponse = AdminDiscountsControllerFindOneResponses[keyof AdminDiscountsControllerFindOneResponses];

export type AdminDiscountsControllerUpdateData = {
    body: UpdateDiscountDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/discounts/{id}';
};

export type AdminDiscountsControllerUpdateResponses = {
    200: AdminDiscountResponseDto;
};

export type AdminDiscountsControllerUpdateResponse = AdminDiscountsControllerUpdateResponses[keyof AdminDiscountsControllerUpdateResponses];

export type AdminPaymentsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        status?: 'pending' | 'completed' | 'failed' | 'refunded';
        /**
         * Filter by order (admin)
         */
        order_id?: string;
        /**
         * Filter by user (admin)
         */
        user_id?: string;
    };
    url: '/admin/payments';
};

export type AdminPaymentsControllerFindAllResponses = {
    200: AdminPaymentPaginatedResponseDto;
};

export type AdminPaymentsControllerFindAllResponse = AdminPaymentsControllerFindAllResponses[keyof AdminPaymentsControllerFindAllResponses];

export type AdminPaymentsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/payments/{id}';
};

export type AdminPaymentsControllerFindOneResponses = {
    200: AdminPaymentResponseDto;
};

export type AdminPaymentsControllerFindOneResponse = AdminPaymentsControllerFindOneResponses[keyof AdminPaymentsControllerFindOneResponses];

export type AdminPaymentsControllerUpdateStatusData = {
    body: UpdatePaymentStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/payments/{id}/status';
};

export type AdminPaymentsControllerUpdateStatusResponses = {
    200: AdminPaymentResponseDto;
};

export type AdminPaymentsControllerUpdateStatusResponse = AdminPaymentsControllerUpdateStatusResponses[keyof AdminPaymentsControllerUpdateStatusResponses];

export type AdminReviewsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        product_id?: string;
        user_id?: string;
        rating?: number;
        isApproved?: boolean;
        isVerified?: boolean;
    };
    url: '/admin/reviews';
};

export type AdminReviewsControllerFindAllResponses = {
    200: AdminReviewPaginatedResponseDto;
};

export type AdminReviewsControllerFindAllResponse = AdminReviewsControllerFindAllResponses[keyof AdminReviewsControllerFindAllResponses];

export type AdminReviewsControllerApproveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/reviews/{id}/approve';
};

export type AdminReviewsControllerApproveResponses = {
    200: AdminReviewResponseDto;
};

export type AdminReviewsControllerApproveResponse = AdminReviewsControllerApproveResponses[keyof AdminReviewsControllerApproveResponses];

export type AdminBannersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        position?: 'hero' | 'promo_strip' | 'mid_page' | 'popup';
    };
    url: '/admin/banners';
};

export type AdminBannersControllerFindAllResponses = {
    200: Array<AdminBannerResponseDto>;
};

export type AdminBannersControllerFindAllResponse = AdminBannersControllerFindAllResponses[keyof AdminBannersControllerFindAllResponses];

export type AdminBannersControllerCreateData = {
    body: CreateBannerDto;
    path?: never;
    query?: never;
    url: '/admin/banners';
};

export type AdminBannersControllerCreateResponses = {
    201: AdminBannerResponseDto;
};

export type AdminBannersControllerCreateResponse = AdminBannersControllerCreateResponses[keyof AdminBannersControllerCreateResponses];

export type AdminBannersControllerUploadImageData = {
    body: {
        file: Blob | File;
        /**
         * true = ảnh mobile, false = ảnh desktop
         */
        isMobile?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/banners/{id}/upload-image';
};

export type AdminBannersControllerUploadImageResponses = {
    200: AdminBannerResponseDto;
};

export type AdminBannersControllerUploadImageResponse = AdminBannersControllerUploadImageResponses[keyof AdminBannersControllerUploadImageResponses];

export type AdminBannersControllerReorderData = {
    body: ReorderBannersDto;
    path?: never;
    query?: never;
    url: '/admin/banners/reorder';
};

export type AdminBannersControllerReorderResponses = {
    204: void;
};

export type AdminBannersControllerReorderResponse = AdminBannersControllerReorderResponses[keyof AdminBannersControllerReorderResponses];

export type AdminBannersControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/banners/{id}';
};

export type AdminBannersControllerRemoveResponses = {
    204: void;
};

export type AdminBannersControllerRemoveResponse = AdminBannersControllerRemoveResponses[keyof AdminBannersControllerRemoveResponses];

export type AdminBannersControllerUpdateData = {
    body: UpdateBannerDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/admin/banners/{id}';
};

export type AdminBannersControllerUpdateResponses = {
    200: AdminBannerResponseDto;
};

export type AdminBannersControllerUpdateResponse = AdminBannersControllerUpdateResponses[keyof AdminBannersControllerUpdateResponses];
